get funcitonallity popup n add api
randomu3/Stellar-burgers pull request #2
Opened 2022-07-03 12:46 UTC by randomu3

2022-07-03 13:26 UTC, andryxxa93 requested changes
Проделана большая работа! Вы хорошо разобрались с функциональными компонентами, правильно используете useEffect и PropTypes.

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- Добавить проверку успешности запроса
- Описать типы содержимого пропсов
- Сделать закрытие модального окна по клику на подолжку

Более подробно описание проблемы смотрите комментарии в pull request.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

Удачных правок!

2022-07-03 13:26 UTC, andryxxa93 commented on src/components/App/app.jsx
>          <section>
**Можно лучше**
Тут можно обойтись без `section`

2022-07-03 13:26 UTC, andryxxa93 commented on src/components/App/app.jsx
> +  }, []);
**Можно лучше**

в дальнейшем добавятся ещё запросы к бэкенду и лучше вынести описание этих запросов в функции

Например:

```
function getIngredients() {
   return fetch(`${NORMA_API}/ingredients`)
    .then(проверка ответа)
}

```

и разместить их в отдельном файле  `utils/burger-api.js`, а не описывать запросы в самом компоненте

2022-07-03 13:26 UTC, andryxxa93 commented on src/components/App/app.jsx
> +      .then(({ data }) => {
**Надо исправить**
Добавьте проверку ответа сервера - res.ok:

Например:

```
.then(res => res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
```

иначе сейчас, если сервер ответи не кодом 2xx, а какой либо ошибкой (4xx, 5xx) мы не попадем в catch т.к. в этом случае fetch не выбрасывает ошибку, мы попытаемся отрисовать данные, хотя они не пришли, в итоге на попытке отрисовки несуществующих данных упадет все приложение

[https://learn.javascript.ru/fetch](https://learn.javascript.ru/fetch)

[https://developer.mozilla.org/en-US/docs/Web/API/Response/ok](https://developer.mozilla.org/en-US/docs/Web/API/Response/ok)

Т.к. эта проверка нужна у всех запросов, лучше вынести её в отдельную функцию

```
const checkReponse = (res) => {
  return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
};
```

`fetch(someUrl).then(checkReponse)`

2022-07-03 13:26 UTC, andryxxa93 commented on src/components/App/app.jsx
> +        console.log(error);
**Можно улучшить**
Console.log нужен только для процесса разработки, перед сдачей проекта его нужно удалять, иначе она будет загружать консоль ненужной, а возможно и приватной информацией. А ошибку лучше записывать в state и показывать пользователю, чтобы он понимал, что происходит.

2022-07-03 13:26 UTC, andryxxa93 commented on src/components/ModalOverlay/ModalOverlay.jsx
> +            {children}
**Можно лучше**

у ModalOverlay не должно быть children, это просто компонент подложки а не контейнер`

2022-07-03 13:26 UTC, andryxxa93 commented on src/components/ModalOverlay/ModalOverlay.jsx
> +        <div className={modalOverlayStyles.wrapper}>
**Необходимо исправить**
Модальное окно должно закрываться по нажатию мышкой на подложку - `modalOverlay`

2022-07-03 13:26 UTC, andryxxa93 commented on src/components/Modal/Modal.jsx
> +      if (e.key === "Escape") {
**Здорово** 
Вы реализовали закрытие модальных окон помощью клика на оверлей и ESC!

2022-07-03 13:26 UTC, andryxxa93 commented on src/components/Modal/Modal.jsx
> +    return () => document.removeEventListener("keydown", handleKeydown);
**Отлично!**
Вы сделали отписку от слушателя, это позволит избежать утечек памяти.

2022-07-03 13:26 UTC, andryxxa93 commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +            ingredients={ingredients.filter((e) => e.type === "bun")}
**Можно улучшить**
Тут есть повторение функции фильтрации, её желательно вынести в отдельную универсальную функцию.

2022-07-03 13:26 UTC, andryxxa93 commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +  ingredients: PropTypes.array.isRequired,
**Необходимо исправить**
Необходимо описать содержимое ингредиентов. Желательно сделать это в отдельном файле, чтобы можно было переиспользовать. Например 
```
export const ingredientPropType = PropTypes.shape({
  _id: PropTypes.string.isRequired,
  name: PropTypes.string.isRequired,
  type: PropTypes.oneOf(["bun", "main", "sauce"]).isRequired,
  proteins: PropTypes.number.isRequired,
  fat: PropTypes.number.isRequired,
  ....
});
```

2022-07-04 17:40 UTC, andryxxa93 requested changes
Всё хорошо, но при запуске проекта выдаёт две ошибки. Исправьте их и ваша работа будет принята. 
<img width="1440" alt="Снимок экрана 2022-07-04 в 20 39 55" src="https://user-images.githubusercontent.com/60173362/177199694-73e9371a-193e-403f-b283-1c4eac317699.png">

2022-07-08 05:27 UTC, andryxxa93 requested changes
Остались ошибки в путях. Я отметил где именно и как исправить, сделайте это и я приму вашу работу

2022-07-08 05:27 UTC, andryxxa93 commented on src/index.tsx
> +import { App } from './components/app/app';
**Необходимо исправить**
Тут ошибка. Директория с заглавной буквы - `App`, а у вас путь со строчной. Нужно так - `import { App } from './components/App/app';`

2022-07-08 05:27 UTC, andryxxa93 commented on src/components/App/app.jsx
> +import { AppHeader } from "../header/header";
**Необходимо исправить**
Должно быть вот так `import { AppHeader } from "../Header/header";`

2022-07-08 05:27 UTC, andryxxa93 commented on src/components/ingredient-details/ingredient-details.jsx
> +import { Modal } from "../modal/modal";
**Необходимо исправить**
Должно быть вот так - ` import { Modal } from "../Modal/Modal"`;

2022-07-08 05:27 UTC, andryxxa93 commented on src/components/order-details/order-details.jsx
> +import { Modal } from "../modal/modal";
**Необходимо исправить**
Должно быть вот так - import { Modal } from "../Modal/Modal";

2022-07-08 05:27 UTC, andryxxa93 commented on src/components/Modal/Modal.jsx
> +import modalStyles from "./modal.module.css";
**Необходимо исправить**
Должно быть вот так - `import modalStyles from "./Modal.module.css";`

2022-07-08 14:01 UTC, randomu3 commented
Как я понял, нужно было просто название папок сделать с заглавной а название файлов оставить как есть. Но момент с Модал не понял, подумал Вы ошиблись.

2022-07-08 14:01 UTC, randomu3 commented
Надеюсь касательно Модал должно было также, но название файла jsx делать Modal - была ваша ошибка. Ато сравнивая, повторюсь, с Header/header - вы указали "так".

2022-07-09 08:24 UTC, andryxxa93 commented
У вас регистр букв в путях не соответствует регистру в директориях. Например - есть директория `App` с файлом `app.jsx`. У вас путь к нему в `index.tsx` - `import { App } from './components/app/app'. При попытке запуска проекта выходит ошибка. Ошибка возникает только на регистрозависимых системах. 
Я принимаю вашу работу, но в будущем учтите этот момент.

2022-07-09 08:25 UTC, andryxxa93 approved these changes

2022-07-09 08:58 UTC, randomu3 commented
Я все равно не понял что не так, Вы сообщаете что у меня > `import { App } from './components/app/app'.

Хотя в файле index.tsx у меня следующее - import { App } from './components/App/app';

2022-07-09 09:07 UTC, randomu3 commented
Перепроверил. Я просто не сделал комит и отправил вам ветку без изменений на проверку) Извиняюсь)

2022-07-09 09:20 UTC, merged